SELECT * FROM gitup1.cleaned_retail_dataset;

# clean the data
select count(*) from gitup1.cleaned_retail_dataset;

 #rename
 alter table gitup1.cleaned_retail_dataset rename to clean_retal;
 
 select * from clean_retal;
SHOW TABLES;
SELECT *
FROM clean_retail
LIMIT 10000;
 
#clean gender
UPDATE clean_retal
 SET Gender =
    CASE
        WHEN Gender IN ('M', 'Male', 'male', 'MALE') THEN 'Male'
        WHEN Gender IN ('F', 'Female', 'female', 'FEMALE') THEN 'Female'
        WHEN Gender IN ('nan', 'NaN', '') THEN NULL
        ELSE NULL
        
    END;
#1. What is the total revenue generated by male vs. female customer
SELECT
    CASE
        WHEN Gender IN ('Male', 'M') THEN 'Male'
        WHEN Gender IN ('Female', 'F') THEN 'Female'
        ELSE 'Other'
    END AS gender_group,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal
WHERE Purchase_Amount_USD IS NOT NULL
GROUP BY
    CASE
        WHEN Gender IN ('Male', 'M') THEN 'Male'
        WHEN Gender IN ('Female', 'F') THEN 'Female'
        ELSE 'Other'
    END;
 

#Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    Customer_ID, Purchase_Amount_USD FROM clean_retal
WHERE Discount_Applied = 'Yes'
  AND Purchase_Amount_USD >
      (SELECT AVG(Purchase_Amount_USD)
       FROM clean_retal);
       
       # business problem

#Do discounts actually increase high-value purchases?       
       SELECT
    Discount_Applied,
    AVG(Purchase_Amount_USD) AS avg_spend
FROM clean_retal
GROUP BY Discount_Applied;



#Which age group spends the most?
SELECT
    Age_Group,
    SUM(Purchase_Amount_USD) AS total_spent
FROM clean_retal
GROUP BY Age_Group;

#Which product categories drive the highest revenue?
SELECT
    Item_Purchased,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal
GROUP BY Item_Purchased
ORDER BY total_revenue DESC;

#Who are the top 10 highest-spending customers?
SELECT
    Customer_ID,
    SUM(Purchase_Amount_USD) AS total_spent
FROM clean_retal
GROUP BY Customer_ID
ORDER BY total_spent DESC
LIMIT 10;

#Are loyalty members spending more than non-members?
SELECT
    Customer_Segment,
    AVG(Purchase_Amount_USD) AS avg_spend
FROM clean_retal
GROUP BY Customer_Segment;

#Which locations are highly dependent on discounts?
SELECT
    Location,
    COUNT(*) AS discount_usage
FROM clean_retal
WHERE Discount_Applied = 'Yes'
GROUP BY Location
ORDER BY discount_usage DESC;


#Which locations generate the most revenue?
SELECT
    Location,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal
GROUP BY Location
ORDER BY total_revenue DESC;

#What percentage of customers use discounts
SELECT
    Discount_Applied,
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM clean_retal) AS percentage
FROM clean_retal
GROUP BY Discount_Applied;

#Which customers used discounts but still spent above average?
SELECT  Customer_ID, Purchase_Amount_USD
FROM clean_retal
WHERE Discount_Applied = 'Yes'
  AND Purchase_Amount_USD >
      (SELECT AVG(Purchase_Amount_USD)
       FROM clean_retal);
       
       #What is the average spending per product category per customer segment?
       SELECT
    Customer_Segment,
    Category,
    AVG(Purchase_Amount_USD) AS avg_spend
FROM clean_retal
GROUP BY Customer_Segment, Category;

#Are review rating customers actually spending more?
SELECT
   Review_Rating ,
    AVG(Purchase_Amount_USD) AS avg_product_spend
FROM clean_retal
GROUP BY Review_Rating;
 
 #Which customer segment is most price-sensitive?
 SELECT
    Customer_Segment,
    COUNT(*) AS discounted_purchases
FROM clean_retal
WHERE Discount_Applied = 'Yes'
GROUP BY Customer_Segment;

#Which product categories sell well even without discounts?
SELECT
    Category,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal
WHERE Discount_Applied = 'No'
GROUP BY Category
ORDER BY total_revenue DESC;








       
       #Which customer gender generates the highest revenue?
       SELECT
    Gender,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal
GROUP BY Gender;



#What is the revenue contribution of loyalty members vs non-members?
SELECT
    Customer_Segment,
    SUM(Purchase_Amount_USD) AS total_revenue
FROM clean_retal 
group by Customer_Segment;





Q3. Which are the top 5 products with the highest average review rating?
SQL Query
SELECT
    Product_Name,
    AVG(Review_Rating) AS avg_rating
FROM clean_retal
GROUP BY Product_Name
ORDER BY avg_rating DESC
LIMIT 5;

Line-by-Line Explanation

SELECT Product_Name → selects each product

AVG(Review_Rating) → calculates average customer rating per product

FROM clean_retal → source table

GROUP BY Product_Name → aggregates ratings by product

ORDER BY avg_rating DESC → highest-rated products first

LIMIT 5 → returns only top 5 products

🔴 Q4. Compare the average purchase amounts between Standard and Express Shipping.
SQL Query
SELECT
    Shipping_Type,
    AVG(Purchase_Amount_USD) AS avg_purchase
FROM clean_retal
GROUP BY Shipping_Type;